In [1]:
import pandas as pd

In [2]:
df = pd.read_json('FIR_details.json')
df.head()

,image_id,bbox,score,category_id,image_name,text
0,452,"[345.3876647949219, 94.77111053466797, 388.078...",0.974434,1,Electronics Complex PS5__1.jpg,2019
1,452,"[273.92877197265625, 92.39881134033203, 313.62...",0.928902,0,Electronics Complex PS5__1.jpg,Electronics Complex
2,452,"[197.4983673095703, 112.17855834960938, 297.28...",0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.
3,563,"[419.6512451171875, 59.593570709228516, 461.42...",0.975759,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017
4,563,"[228.6677703857422, 59.94287872314453, 270.955...",0.883566,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017

In [3]:
image_names = sorted(df["image_name"].unique())

In [4]:
image_names

['Airport PSAIRPORT-0004-2017-2711__1.jpg',
 'Airport PSAIRPORT-0004-2018-3503__1.jpg',
 'Airport PSAIRPORT-0005-2017-3336__1.jpg',
 'Airport PSAIRPORT-0005-2018-1983__1.jpg',
 'Airport PSAIRPORT-0006-2017-3301__1.jpg',
 'Airport PSAIRPORT-0006-2018-1899__1.jpg',
 'Airport PSAIRPORT-0007-2017-3336__1.jpg',
 'Airport PSAIRPORT-0007-2018-1932__1.jpg',
 'Airport PSAIRPORT-0008-2017-3243__1.jpg',
 'Airport PSAIRPORT-0008-2018-2110__1.jpg',
 'Airport PSAIRPORT-0009-2017-3638__1.jpg',
 'Airport PSAIRPORT-0009-2018-3628__1.jpg',
 'Airport PSAIRPORT-0010-2017-3678__1.jpg',
 'Airport PSAIRPORT-0010-2018-3706__1.jpg',
 'Airport PSAIRPORT-0011-2017-4014__1.jpg',
 'Airport PSAIRPORT-0011-2018-3453__1.jpg',
 'Airport PSAIRPORT-0012-2017-4052__1.jpg',
 'Airport PSAIRPORT-0012-2018-3495__1.jpg',
 'Airport PSAIRPORT-0013-2017-4063__1.jpg',
 'Airport PSAIRPORT-0013-2018-3843__1.jpg',
 'Airport PSAIRPORT-0014-2017-4221__1.jpg',
 'Airport PSAIRPORT-0014-2018-4861__1.jpg',
 'Airport PSAIRPORT-0015-2017-4215__1.jpg',
 'Airport PSAIRPORT-0015-2018-5219__1.jpg',
 'Airport PSAIRPORT-0016-2017-4225__1.jpg',
 'Airport PSAIRPORT-0016-2018-5562__1.jpg',
 'Airport PSAIRPORT-0017-2017-4472__1.jpg',
 'Airport PSAIRPORT-0017-2018-6685__1.jpg',
 'Airport PSAIRPORT-0018-2017-1390__1.jpg',
 'Airport PSAIRPORT-0018-2018-9649__1.jpg',
 'Airport PSAIRPORT-0019-2017-4398__1.jpg',
 'Airport PSAIRPORT-0019-2018-1020__1.jpg',
 'Airport PSAIRPORT-0020-2017-4612__1.jpg',
 'Airport PSAIRPORT-0020-2018-9535__1.jpg',
 'Airport PSAIRPORT-0021-2017-4783__1.jpg',
 'Airport PSAIRPORT-0021-2018-2312__1.jpg',
 'Airport PSAIRPORT-0022-2017-4797__1.jpg',
 'Airport PSAIRPORT-0022-2018-2306__1.jpg',
 'Airport PSAIRPORT-0023-2018-2380__1.jpg',
 'Airport PSAIRPORT-0024-2017-5230__1.jpg',
 'Airport PSAIRPORT-0024-2018-2372__1.jpg',
 'Airport PSAIRPORT-0025-2017-5144__1.jpg',
 'Airport PSAIRPORT-0026-2017-5762__1.jpg',
 'Airport PSAIRPORT-0026-2018-2718__1.jpg',
 'Airport PSAIRPORT-0027-2017-4310__1.jpg',
 'Airport PSAIRPORT-0027-2018-3288__1.jpg',
 'Airport PSAIRPORT-0028-2017-3873__1.jpg',
 'Airport PSAIRPORT-0028-2018-3687__1.jpg',
 'Airport PSAIRPORT-0029-2017-4006__1.jpg',
 'Airport PSAIRPORT-0029-2018-3721__1.jpg',
 'Airport PSAIRPORT-0030-2017-1970__1.jpg',
 'Airport PSAIRPORT-0030-2018-3632__1.jpg',
 'Airport PSAIRPORT-0031-2018-3685__1.jpg',
 'Airport PSAIRPORT-0032-2017-1992__1.jpg',
 'Airport PSAIRPORT-0032-2018-3668__1.jpg',
 'Airport PSAIRPORT-0033-2017-1971__1.jpg',
 'Airport PSAIRPORT-0033-2018-3668__1.jpg',
 'Airport PSAIRPORT-0034-2017-1907__1.jpg',
 'Airport PSAIRPORT-0034-2018-3706__1.jpg',
 'Airport PSAIRPORT-0035-2017-1998__1.jpg',
 'Airport PSAIRPORT-0035-2018-3809__1.jpg',
 'Airport PSAIRPORT-0036-2017-2353__1.jpg',
 'Airport PSAIRPORT-0036-2018-3858__1.jpg',
 'Airport PSAIRPORT-0037-2017-2758__1.jpg',
 'Airport PSAIRPORT-0037-2018-3277__1.jpg',
 'Airport PSAIRPORT-0038-2017-3070__1.jpg',
 'Airport PSAIRPORT-0038-2018-3233__1.jpg',
 'Airport PSAIRPORT-0039-2017-3123__1.jpg',
 'Airport PSAIRPORT-0039-2018-3100__1.jpg',
 'Airport PSAIRPORT-0040-2017-3229__1.jpg',
 'Airport PSAIRPORT-0040-2018-3130__1.jpg',
 'Airport PSAIRPORT-0041-2017-3309__1.jpg',
 'Airport PSAIRPORT-0041-2018-3121__1.jpg',
 'Airport PSAIRPORT-0042-2017-3277__1.jpg',
 'Airport PSAIRPORT-0042-2018-3079__1.jpg',
 'Airport PSAIRPORT-0043-2017-3250__1.jpg',
 'Airport PSAIRPORT-0043-2018-3085__1.jpg',
 'Airport PSAIRPORT-0044-2017-4985__1.jpg',
 'Airport PSAIRPORT-0044-2018-1206__1.jpg',
 'Airport PSAIRPORT-0045-2017-5032__1.jpg',
 'Airport PSAIRPORT-0045-2018-3130__1.jpg',
 'Airport PSAIRPORT-0046-2017-4970__1.jpg',
 'Airport PSAIRPORT-0046-2018-2859__1.jpg',
 'Airport PSAIRPORT-0047-2017-4994__1.jpg',
 'Airport PSAIRPORT-0047-2018-3672__1.jpg',
 'Airport PSAIRPORT-0048-2017-2735__1.jpg',
 'Airport PSAIRPORT-0048-2018-3695__1.jpg',
 'Airport PSAIRPORT-0049-2017-1329__1.jpg',
 'Airport PSAIRPORT-0049-2018-3619__1.jpg',
 'Airport PSAIRPORT-0050-2017-1335__1.jpg',
 'Airport PSAIRPORT-0050-2018-3683__1.jpg',
 'Airport PSAIRPORT-0051-2017-1415__1.jpg',
 'Airport PSAIRPORT-0051-2018-3615__1.jpg',
 'Airport PSAIRPORT-0052-2017-2718__1.jpg',
 'Airport PSAIRPORT-0052-2018-3609__1.jpg',
 'Airport PSAIRPORT-0053-2017-2737__1.jpg',
 'Airport PSAIRPORT-0053-2018-3700__1.jpg',
 'Airport PSAIRPORT-0054-2017-2760__1.jpg',
 'Airport PSAIRPORT-0054-2018-3634__1.jpg',
 'Baguiati PS500-18__1.jpg',
 'Baguiati PS500-19__1.jpg',
 'Baguiati PS500-2021__1.jpg',
 'Baguiati PS501-18__1.jpg',
 'Baguiati PS501-19__1.jpg',
 'Baguiati PS501-2021__1.jpg',
 'Baguiati PS502-18__1.jpg',
 'Baguiati PS502-19__1.jpg',
 'Baguiati PS502-2021__1.jpg',
 'Baguiati PS503-18__1.jpg',
 'Baguiati PS503-19__1.jpg',
 'Baguiati PS503-2021__1.jpg',
 'Baguiati PS504-18__1.jpg',
 'Baguiati PS504-19__1.jpg',
 'Baguiati PS504-2021__1.jpg',
 'Baguiati PS505-18__1.jpg',
 'Baguiati PS505-19__1.jpg',
 'Baguiati PS505-2021__1.jpg',
 'Baguiati PS506-18__1.jpg',
 'Baguiati PS506-19__1.jpg',
 'Baguiati PS506-2021__1.jpg',
 'Baguiati PS507-18__1.jpg',
 'Baguiati PS507-19__1.jpg',
 'Baguiati PS507-2021__1.jpg',
 'Baguiati PS508-18__1.jpg',
 'Baguiati PS508-19__1.jpg',
 'Baguiati PS508-2021__1.jpg',
 'Baguiati PS509-18__1.jpg',
 'Baguiati PS509-19__1.jpg',
 'Baguiati PS509-2021__1.jpg',
 'Baguiati PS510-18__1.jpg',
 'Baguiati PS510-19__1.jpg',
 'Baguiati PS510-2021__1.jpg',
 'Baguiati PS511-18__1.jpg',
 'Baguiati PS511-19__1.jpg',
 'Baguiati PS511-2021__1.jpg',
 'Baguiati PS512-18__1.jpg',
 'Baguiati PS512-19__1.jpg',
 'Baguiati PS512-2021__1.jpg',
 'Baguiati PS513-18__1.jpg',
 'Baguiati PS513-19__1.jpg',
 'Baguiati PS513-2021__1.jpg',
 'Baguiati PS514-18__1.jpg',
 'Baguiati PS514-19__1.jpg',
 'Baguiati PS514-2021__1.jpg',
 'Baguiati PS515-18__1.jpg',
 'Baguiati PS515-19__1.jpg',
 'Baguiati PS516-18__1.jpg',
 'Baguiati PS516-19__1.jpg',
 'Baguiati PS516-2021__1.jpg',
 'Baguiati PS517-18__1.jpg',
 'Baguiati PS517-19__1.jpg',
 'Baguiati PS517-2021__1.jpg',
 'Baguiati PS518-18__1.jpg',
 'Baguiati PS518-19__1.jpg',
 'Baguiati PS518-2021__1.jpg',
 'Baguiati PS519-18__1.jpg',
 'Baguiati PS519-19__1.jpg',
 'Baguiati PS519-2021__1.jpg',
 'Baguiati PS520-18__1.jpg',
 'Baguiati PS520-19__1.jpg',
 'Baguiati PS520-2021__1.jpg',
 'Baguiati PS521-18__1.jpg',
 'Baguiati PS521-19__1.jpg',
 'Baguiati PS521-2021__1.jpg',
 'Baguiati PS522-18__1.jpg',
 'Baguiati PS522-19__1.jpg',
 'Baguiati PS522-2021__1.jpg',
 'Baguiati PS523-18__1.jpg',
 'Baguiati PS523-19__1.jpg',
 'Baguiati PS523-2021__1.jpg',
 'Baguiati PS524-18__1.jpg',
 'Baguiati PS524-2021__1.jpg',
 'Baguiati PS525-18__1.jpg',
 'Baguiati PS525-2021__1.jpg',
 'Baguiati PS526-18__1.jpg',
 'Baguiati PS526-2021__1.jpg',
 'Baguiati PS527-18__1.jpg',
 'Baguiati PS527-19__1.jpg',
 'Baguiati PS527-2021__1.jpg',
 'Baguiati PS528-18__1.jpg',
 'Baguiati PS528-2021__1.jpg',
 'Baguiati PS529-18__1.jpg',
 'Baguiati PS529-2021__1.jpg',
 'Baguiati PS530-18__1.jpg',
 'Baguiati PS530-2021__1.jpg',
 'Baguiati PS531-18__1.jpg',
 'Baguiati PS531-2021__1.jpg',
 'Baguiati PS532-18__1.jpg',
 'Baguiati PS532-2021__1.jpg',
 'Baguiati PS533-18__1.jpg',
 'Baguiati PS533-2021__1.jpg',
 'Baguiati PS534-18__1.jpg',
 'Baguiati PS534-2021__1.jpg',
 'Baguiati PS535-18__1.jpg',
 'Baguiati PS535-2021__1.jpg',
 'Baguiati PS536-18__1.jpg',
 'Baguiati PS536-2021__1.jpg',
 'Baguiati PS537-18__1.jpg',
 'Baguiati PS537-2021__1.jpg',
 'Baguiati PS538-18__1.jpg',
 'Baguiati PS538-2021__1.jpg',
 'Baguiati PS539-18__1.jpg',
 'Baguiati PS539-2021__1.jpg',
 'Baguiati PS540-18__1.jpg',
 'Baguiati PS540-2021__1.jpg',
 'Baguiati PS541-18__1.jpg',
 'Baguiati PS541-2021__1.jpg',
 'Baguiati PS542-18__1.jpg',
 'Baguiati PS542-2021__1.jpg',
 'Baguiati PS543-18__1.jpg',
 'Baguiati PS543-2021__1.jpg',
 'Baguiati PS544-18__1.jpg',
 'Baguiati PS544-2021__1.jpg',
 'Baguiati PS545-18__1.jpg',
 'Baguiati PS545-2021__1.jpg',
 'Baguiati PS546-18__1.jpg',
 'Baguiati PS546-2021__1.jpg',
 'Baguiati PS547-18__1.jpg',
 'Baguiati PS547-2021__1.jpg',
 'Baguiati PS548-18__1.jpg',
 'Baguiati PS548-2021__1.jpg',
 'Baguiati PS549-18__1.jpg',
 'Baguiati PS549-2021__1.jpg',
 'Baguiati PS550-18__1.jpg',
 'Baguiati PS550-2021__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0200-2017-4289__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0201-2017-4187__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0202-2017-4251__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0203-2017-4270__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0205-2017-1730__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0207-2017-1747__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0208-2017-2524__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0209-2017-2574__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0210-2017-2578__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0211-2017-2475__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0212-2017-2522__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0213-2017-2509__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0214-2017-2568__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0215-2017-2477__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0216-2017-3672__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0217-2017-3628__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0218-2017-3621__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0219-2017-3662__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0221-2017-5340__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0222-2017-5361__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0223-2017-5333__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0224-2017-5429__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0225-2017-5961__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0226-2017-5903__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0227-2017-5975__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0228-2017-5944__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0229-2017-5999__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0230-2017-5923__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0231-2017-5927__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0232-2017-5912__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0233-2017-5916__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0234-2017-5933__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0235-2017-5971__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0236-2017-5920__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0237-2017-8509__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0238-2017-7825__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0239-2017-1973__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0240-2017-1911__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0241-2017-1937__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0242-2017-4759__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0243-2017-4780__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0244-2017-4806__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0245-2017-4850__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0246-2017-2293__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0247-2017-2357__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0248-2017-4626__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0249-2017-2338__1.jpg',
 'Bidhannagar North PSBDN-NORTH-0250-2017-2334__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0100-2017-4941__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0101-2017-5779__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0102-2017-4253__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0103-2017-4177__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0104-2017-1191__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0105-2017-1202__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0106-2017-1612__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0107-2017-1578__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0108-2017-1983__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0109-2017-2365__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0110-2017-3132__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0111-2017-3455__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0112-2017-4196__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0113-2017-5336__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0114-2017-5764__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0115-2017-5789__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0116-2017-5733__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0117-2017-7825__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0118-2017-8167__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0119-2017-8072__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0120-2017-8623__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0121-2017-7977__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0122-2017-2304__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0123-2017-3110__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0124-2017-3102__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0125-2017-3484__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0126-2017-4666__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0127-2017-5323__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0128-2017-5391__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0129-2017-5754__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0130-2017-5777__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0131-2017-5735__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0132-2017-6666__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0133-2017-1056__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0134-2017-9877__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0135-2017-2524__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0136-2017-2553__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0137-2017-2921__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0138-2017-3231__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0139-2017-3674__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0140-2017-3704__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0141-2017-4466__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0142-2017-4460__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0143-2017-4823__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0144-2017-4861__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0145-2017-4859__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0146-2017-7844__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0147-2017-7787__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0148-2017-1164__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0149-2017-1181__1.jpg',
 'Bidhannagar South PSBDN-SOUTH-0150-2017-1924__1.jpg',
 'Cyber-Crime PS40-20__1.jpg',
 'Cyber-Crime PS41-20__1.jpg',
 'Cyber-Crime PS42-20__1.jpg',
 'Cyber-Crime PS43-20__1.jpg',
 'Cyber-Crime PS44-20__1.jpg',
 'Cyber-Crime PS45-20__1.jpg',
 'Cyber-Crime PS46-20__1.jpg',
 'Cyber-Crime PS47-20__1.jpg',
 'Cyber-Crime PS48-20__1.jpg',
 'Cyber-Crime PS49-2020__1.jpg',
 'Cyber-Crime PS50-2020__1.jpg',
 'Cyber-Crime PS51-21__1.jpg',
 'Cyber-Crime PS52-21__1.jpg',
 'Cyber-Crime PS52__1.jpg',
 'Cyber-Crime PS53-21__1.jpg',
 'Cyber-Crime PS54-21__1.jpg',
 'Cyber-Crime PS55-21__1.jpg',
 'Cyber-Crime PS56-21__1.jpg',
 'Cyber-Crime PS56__1.jpg',
 'Cyber-Crime PS57-21__1.jpg',
 'Cyber-Crime PS58-21__1.jpg',
 'Cyber-Crime PS59-21__1.jpg',
 'Cyber-Crime PS60-21__1.jpg',
 'Cyber-Crime PS61-21__1.jpg',
 'Cyber-Crime PS63-21__1.jpg',
 'Cyber-Crime PS63__1.jpg',
 'Cyber-Crime PS64%202020__1.jpg',
 'Cyber-Crime PS64-21__1.jpg',
 'Cyber-Crime PS64__1.jpg',
 'ECO PARK PS01__1.jpg',
 'ECO PARK PS02__1.jpg',
 'ECO PARK PS03__1.jpg',
 'ECO PARK PS04__1.jpg',
 'ECO PARK PS05__1.jpg',
 'ECO PARK PS06__1.jpg',
 'ECO PARK PS09__1.jpg',
 'ECO PARK PS10__1.jpg',
 'ECO PARK PS11__1.jpg',
 'ECO PARK PS12__1.jpg',
 'ECO PARK PS13__1.jpg',
 'ECO PARK PS14__1.jpg',
 'ECO PARK PS15__1.jpg',
 'ECO PARK PS16__1.jpg',
 'ECO PARK PS17%20(2)__1.jpg',
 'ECO PARK PS17__1.jpg',
 'ECO PARK PS18__1.jpg',
 'ECO PARK PS19__1.jpg',
 'ECO PARK PS1__1.jpg',
 'ECO PARK PS20__1.jpg',
 'ECO PARK PS21__1.jpg',
 'ECO PARK PS22__1.jpg',
 'ECO PARK PS23__1.jpg',
 'ECO PARK PS24__1.jpg',
 'ECO PARK PS25__1.jpg',
 'ECO PARK PS26__1.jpg',
 'ECO PARK PS27__1.jpg',
 'ECO PARK PS28__1.jpg',
 'ECO PARK PS29__1.jpg',
 'ECO PARK PS2__1.jpg',
 'ECO PARK PS30__1.jpg',
 'ECO PARK PS31__1.jpg',
 'ECO PARK PS32__1.jpg',
 'ECO PARK PS33__1.jpg',
 'ECO PARK PS34__1.jpg',
 'ECO PARK PS35__1.jpg',
 'ECO PARK PS36__1.jpg',
 'ECO PARK PS37__1.jpg',
 'ECO PARK PS38__1.jpg',
 'ECO PARK PS39__1.jpg',
 'ECO PARK PS3__1.jpg',
 'ECO PARK PS40__1.jpg',
 'ECO PARK PS41__1.jpg',
 'ECO PARK PS42__1.jpg',
 'ECO PARK PS43__1.jpg',
 'ECO PARK PS44__1.jpg',
 'ECO PARK PS45__1.jpg',
 'ECO PARK PS46__1.jpg',
 'ECO PARK PS47__1.jpg',
 'ECO PARK PS48__1.jpg',
 'ECO PARK PS49__1.jpg',
 'ECO PARK PS4__1.jpg',
 'ECO PARK PS50__1.jpg',
 'ECO PARK PS51__1.jpg',
 'ECO PARK PS5__1.jpg',
 'ECO PARK PS6__1.jpg',
 'ECO PARK PS7__1.jpg',
 'ECO PARK PS8__1.jpg',
 'ECO PARK PS9__1.jpg',
 'Electronics Complex PS01__1.jpg',
 'Electronics Complex PS02__1.jpg',
 'Electronics Complex PS03-2020__1.jpg',
 'Electronics Complex PS04-2020__1.jpg',
 'Electronics Complex PS05__1.jpg',
 'Electronics Complex PS07__1.jpg',
 'Electronics Complex PS09__1.jpg',
 'Electronics Complex PS1-22__1.jpg',
 'Electronics Complex PS10-19__1.jpg',
 'Electronics Complex PS10-22__1.jpg',
 'Electronics Complex PS10__1.jpg',
 'Electronics Complex PS11-19__1.jpg',
 'Electronics Complex PS11-22__1.jpg',
 'Electronics Complex PS11__1.jpg',
 'Electronics Complex PS12-2020__1.jpg',
 'Electronics Complex PS12-22__1.jpg',
 'Electronics Complex PS12__1.jpg',
 'Electronics Complex PS13-22__1.jpg',
 'Electronics Complex PS13__1.jpg',
 'Electronics Complex PS14-22__1.jpg',
 'Electronics Complex PS14__1.jpg',
 'Electronics Complex PS15-20__1.jpg',
 'Electronics Complex PS15-22__1.jpg',
 'Electronics Complex PS15__1.jpg',
 'Electronics Complex PS16-22__1.jpg',
 'Electronics Complex PS16__1.jpg',
 'Electronics Complex PS1__1.jpg',
 'Electronics Complex PS2-22__1.jpg',
 'Electronics Complex PS2__1.jpg',
 'Electronics Complex PS3-22__1.jpg',
 'Electronics Complex PS3__1.jpg',
 'Electronics Complex PS4-22__1.jpg',
 'Electronics Complex PS4__1.jpg',
 'Electronics Complex PS5-21__1.jpg',
 'Electronics Complex PS5-22__1.jpg',
 'Electronics Complex PS5__1.jpg',
 'Electronics Complex PS6-21__1.jpg',
 'Electronics Complex PS6-22__1.jpg',
 'Electronics Complex PS6__1.jpg',
 'Electronics Complex PS7-22__1.jpg',
 'Electronics Complex PS7__1.jpg',
 'Electronics Complex PS8-21__1.jpg',
 'Electronics Complex PS8-22__1.jpg',
 'Electronics Complex PS8__1.jpg',
 'Electronics Complex PS9-21__1.jpg',
 'Electronics Complex PS9-22__1.jpg',
 'Electronics Complex PS9__1.jpg',
 'Lake Town PS01__1.jpg',
 'Lake Town PS02__1.jpg',
 'Lake Town PS03__1.jpg',
 'Lake Town PS04__1.jpg',
 'Lake Town PS05__1.jpg',
 'Lake Town PS06__1.jpg',
 'Lake Town PS07__1.jpg',
 'Lake Town PS08__1.jpg',
 'Lake Town PS09__1.jpg',
 'Lake Town PS10__1.jpg',
 'Lake Town PS11__1.jpg',
 'Lake Town PS12__1.jpg',
 'Lake Town PS13__1.jpg',
 'Lake Town PS14__1.jpg',
 'Lake Town PS15__1.jpg',
 'Lake Town PS16__1.jpg',
 'Lake Town PS17__1.jpg',
 'Lake Town PS18__1.jpg',
 'Lake Town PS19__1.jpg',
 'Lake Town PS1__1.jpg',
 'Lake Town PS2__1.jpg',
 'Lake Town PS3__1.jpg',
 'Lake Town PS4__1.jpg',
 'Lake Town PS5__1.jpg',
 'Lake Town PS6__1.jpg',
 'Lake Town PS7__1.jpg',
 'Lake Town PS8__1.jpg',
 'Lake Town PS9__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0001-2017-2488__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0002-2018-9706__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0003-2017-2887__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0003-2018-3799__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0004-2017-3235__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0004-2018-5942__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0005-2018-5904__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0008-2017-8566__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0009-2018-2186__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0010-2018-5239__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0011-2017-1590__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0011-2018-4455__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0012-2017-1812__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0013-2017-2114__1.jpg',
 'NSCBI Airport PSNSCBI-AIRPORT-0013-2018-3457__1.jpg',
 'Women PS51__1.jpg',
 'Women PS52__1.jpg',
 'Women PS53__1.jpg',
 'Women PSWOMEN-0001-2018-1189__1.jpg',
 'Women PSWOMEN-0002-2017-2099__1.jpg',
 'Women PSWOMEN-0003-2018-4808__1.jpg',
 'Women PSWOMEN-0004-2018-2872__1.jpg',
 'Women PSWOMEN-0005-2018-3968__1.jpg',
 'Women PSWOMEN-0006-2018-3119__1.jpg',
 'Women PSWOMEN-0007-2018-4620__1.jpg',
 'Women PSWOMEN-0008-2018-4643__1.jpg',
 'Women PSWOMEN-0009-2018-4645__1.jpg',
 'Women PSWOMEN-0010-2017-3294__1.jpg',
 'Women PSWOMEN-0010-2018-5325__1.jpg',
 'Women PSWOMEN-0011-2018-5585__1.jpg',
 'Women PSWOMEN-0012-2017-4054__1.jpg',
 'Women PSWOMEN-0012-2018-3062__1.jpg',
 'Women PSWOMEN-0013-2018-5015__1.jpg',

In [5]:
x0 = []
y0 = []
x1 = []
y1 = []
for i in range(0,len(df)):
    x0.append(int(df['bbox'][i][0]))
    y0.append(int(df['bbox'][i][1]))
    x1.append(int(df['bbox'][i][2]))
    y1.append(int(df['bbox'][i][3]))
df.head()
# ,df['bbox'][1],df['bbox'][2],df['bbox'][3]

,image_id,bbox,score,category_id,image_name,text
0,452,"[345.3876647949219, 94.77111053466797, 388.078...",0.974434,1,Electronics Complex PS5__1.jpg,2019
1,452,"[273.92877197265625, 92.39881134033203, 313.62...",0.928902,0,Electronics Complex PS5__1.jpg,Electronics Complex
2,452,"[197.4983673095703, 112.17855834960938, 297.28...",0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.
3,563,"[419.6512451171875, 59.593570709228516, 461.42...",0.975759,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017
4,563,"[228.6677703857422, 59.94287872314453, 270.955...",0.883566,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017

In [6]:
df['x0']= x0
df['y0']= y0
df['x1']= x1
df['y1']= y1

In [7]:
df.drop(columns=["bbox"], inplace=True)

In [8]:
df.head()

,image_id,score,category_id,image_name,text,x0,y0,x1,y1
0,452,0.974434,1,Electronics Complex PS5__1.jpg,2019,345,94,388,115
1,452,0.928902,0,Electronics Complex PS5__1.jpg,Electronics Complex,273,92,313,113
2,452,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
3,563,0.975759,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017,419,59,461,81
4,563,0.883566,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017,228,59,270,83

In [9]:
df.head()

,image_id,score,category_id,image_name,text,x0,y0,x1,y1
0,452,0.974434,1,Electronics Complex PS5__1.jpg,2019,345,94,388,115
1,452,0.928902,0,Electronics Complex PS5__1.jpg,Electronics Complex,273,92,313,113
2,452,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
3,563,0.975759,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017,419,59,461,81
4,563,0.883566,1,Women PSWOMEN-0032-2017-1422__1.jpg,2017,228,59,270,83

In [10]:
df_cat_2 = df[df['category_id']==2].copy()
df_cat_2.head()

,image_id,score,category_id,image_name,text,x0,y0,x1,y1
2,452,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
13,143,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
17,130,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
21,144,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
28,169,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [11]:
# df_cat_2.drop(columns=["category_id"], inplace=True)
df_cat_2.head()

,image_id,score,category_id,image_name,text,x0,y0,x1,y1
2,452,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
13,143,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
17,130,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
21,144,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
28,169,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [12]:
df_cat_2.drop(columns=["image_id"], inplace=True)

In [13]:
df_cat_2.head()

,score,category_id,image_name,text,x0,y0,x1,y1
2,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
13,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
17,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
21,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
28,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [14]:
df_cat_2 = df_cat_2.reset_index()
df_cat_2.head()

,index,score,category_id,image_name,text,x0,y0,x1,y1
0,2,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
1,13,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
2,17,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
3,21,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
4,28,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [15]:
df_cat_2.drop(columns=["index"], inplace=True)
df_cat_2.head()

,score,category_id,image_name,text,x0,y0,x1,y1
0,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
1,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
2,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
3,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
4,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [16]:
df_cat_2.head()

,score,category_id,image_name,text,x0,y0,x1,y1
0,0.789916,2,Electronics Complex PS5__1.jpg,420/406/34 Ipc.,197,112,297,136
1,0.520320,2,Baguiati PS514-18__1.jpg,"135(I)(A) Of Electricity Act, 2003",443,126,696,150
2,0.921957,2,Baguiati PS509-2021__1.jpg,341/323/506/34 Ipc,495,142,648,169
3,0.904128,2,Baguiati PS514-19__1.jpg,341/186/188/506/34 Ipc,485,160,636,184
4,0.935657,2,Baguiati PS523-18__1.jpg,341/325/34 Ipc,509,142,646,164

In [17]:
text_column = df_cat_2.pop('text')

In [18]:
df_cat_2.insert(6,'my_text', text_column)

In [19]:
df_cat_2.head()

,score,category_id,image_name,x0,y0,x1,my_text,y1
0,0.789916,2,Electronics Complex PS5__1.jpg,197,112,297,420/406/34 Ipc.,136
1,0.520320,2,Baguiati PS514-18__1.jpg,443,126,696,"135(I)(A) Of Electricity Act, 2003",150
2,0.921957,2,Baguiati PS509-2021__1.jpg,495,142,648,341/323/506/34 Ipc,169
3,0.904128,2,Baguiati PS514-19__1.jpg,485,160,636,341/186/188/506/34 Ipc,184
4,0.935657,2,Baguiati PS523-18__1.jpg,509,142,646,341/325/34 Ipc,164

In [20]:
df_cat_2.head()

,score,category_id,image_name,x0,y0,x1,my_text,y1
0,0.789916,2,Electronics Complex PS5__1.jpg,197,112,297,420/406/34 Ipc.,136
1,0.520320,2,Baguiati PS514-18__1.jpg,443,126,696,"135(I)(A) Of Electricity Act, 2003",150
2,0.921957,2,Baguiati PS509-2021__1.jpg,495,142,648,341/323/506/34 Ipc,169
3,0.904128,2,Baguiati PS514-19__1.jpg,485,160,636,341/186/188/506/34 Ipc,184
4,0.935657,2,Baguiati PS523-18__1.jpg,509,142,646,341/325/34 Ipc,164

In [21]:
cat_id_column = df_cat_2.pop('category_id')

In [22]:
df_cat_2.insert(6,'label', cat_id_column)

In [23]:
df_cat_2.head()

,score,image_name,x0,y0,x1,my_text,label,y1
0,0.789916,Electronics Complex PS5__1.jpg,197,112,297,420/406/34 Ipc.,2,136
1,0.520320,Baguiati PS514-18__1.jpg,443,126,696,"135(I)(A) Of Electricity Act, 2003",2,150
2,0.921957,Baguiati PS509-2021__1.jpg,495,142,648,341/323/506/34 Ipc,2,169
3,0.904128,Baguiati PS514-19__1.jpg,485,160,636,341/186/188/506/34 Ipc,2,184
4,0.935657,Baguiati PS523-18__1.jpg,509,142,646,341/325/34 Ipc,2,164

In [24]:
# df_cat_2.to_csv("processed_dataset.csv", index=False)

In [25]:
df_cat_2.sort_values("image_name",axis=0)

,score,image_name,x0,y0,x1,my_text,label,y1
331,0.869296,Airport PSAIRPORT-0004-2017-2711__1.jpg,559,83,653,399/402 Ipc And 25(I)(A)/27 Arms Act,2,110
170,0.964737,Airport PSAIRPORT-0004-2018-3503__1.jpg,393,152,529,420/406/120B Ipc,2,178
339,0.717034,Airport PSAIRPORT-0005-2017-3336__1.jpg,462,65,595,323/380/506/120B Ipc,2,88
40,0.662735,Airport PSAIRPORT-0006-2017-3301__1.jpg,535,81,689,498A/448/326 Ipc,2,108
485,0.734326,Airport PSAIRPORT-0006-2018-1899__1.jpg,432,120,639,323/307/497/498A/406/506/34 And 3/4 Dp Act,2,151
...,...,...,...,...,...,...,...,...
11,0.770835,Women PSWOMEN-0025-2017-3083__1.jpg,425,160,608,341/323/354A/379/506(Ii)/509/34 Ipc,2,185
312,0.585852,Women PSWOMEN-0030-2017-8528__1.jpg,610,152,653,498A/406/34 Ipc,2,175
344,0.647267,Women PSWOMEN-0031-2017-1217__1.jpg,564,151,626,195A/120B Ipc,2,178
521,0.844651,Women PSWOMEN-0035-2017-1610__1.jpg,469,105,578,498A/325/313/406/34 Ipc And Sec 3/4 Dp Act,2,131
319,0.769234,Women PSWOMEN-0036-2017-4052__1.jpg,223,131,330,498A/406/34 Ipc,2,160

In [26]:
box_df = df_cat_2.copy()

In [27]:
# box_df.drop(columns=["image_name"], inplace=True)
box_df.head()

,score,image_name,x0,y0,x1,my_text,label,y1
0,0.789916,Electronics Complex PS5__1.jpg,197,112,297,420/406/34 Ipc.,2,136
1,0.520320,Baguiati PS514-18__1.jpg,443,126,696,"135(I)(A) Of Electricity Act, 2003",2,150
2,0.921957,Baguiati PS509-2021__1.jpg,495,142,648,341/323/506/34 Ipc,2,169
3,0.904128,Baguiati PS514-19__1.jpg,485,160,636,341/186/188/506/34 Ipc,2,184
4,0.935657,Baguiati PS523-18__1.jpg,509,142,646,341/325/34 Ipc,2,164

In [28]:
box_df.drop(columns=["my_text"], inplace=True)
box_df.head()

      score                      image_name   x0   y0   x1  label   y1
0  0.789916  Electronics Complex PS5__1.jpg  197  112  297      2  136
1  0.520320        Baguiati PS514-18__1.jpg  443  126  696      2  150
2  0.921957      Baguiati PS509-2021__1.jpg  495  142  648      2  169
3  0.904128        Baguiati PS514-19__1.jpg  485  160  636      2  184
4  0.935657        Baguiati PS523-18__1.jpg  509  142  646      2  164

In [29]:
len(box_df)

537

In [30]:
box_df.drop(columns = ["label"], inplace=True)

In [31]:
box_df.head()

      score                      image_name   x0   y0   x1   y1
0  0.789916  Electronics Complex PS5__1.jpg  197  112  297  136
1  0.520320        Baguiati PS514-18__1.jpg  443  126  696  150
2  0.921957      Baguiati PS509-2021__1.jpg  495  142  648  169
3  0.904128        Baguiati PS514-19__1.jpg  485  160  636  184
4  0.935657        Baguiati PS523-18__1.jpg  509  142  646  164

In [32]:
box_df.sort_values(["image_name", "score"], ascending = [True, False])

        score                               image_name   x0   y0   x1   y1
331  0.869296  Airport PSAIRPORT-0004-2017-2711__1.jpg  559   83  653  110
170  0.964737  Airport PSAIRPORT-0004-2018-3503__1.jpg  393  152  529  178
339  0.717034  Airport PSAIRPORT-0005-2017-3336__1.jpg  462   65  595   88
40   0.662735  Airport PSAIRPORT-0006-2017-3301__1.jpg  535   81  689  108
485  0.734326  Airport PSAIRPORT-0006-2018-1899__1.jpg  432  120  639  151
..        ...                                      ...  ...  ...  ...  ...
11   0.770835      Women PSWOMEN-0025-2017-3083__1.jpg  425  160  608  185
312  0.585852      Women PSWOMEN-0030-2017-8528__1.jpg  610  152  653  175
344  0.647267      Women PSWOMEN-0031-2017-1217__1.jpg  564  151  626  178
521  0.844651      Women PSWOMEN-0035-2017-1610__1.jpg  469  105  578  131
319  0.769234      Women PSWOMEN-0036-2017-4052__1.jpg  223  131  330  160

[537 rows x 6 columns]

In [33]:
box_df["image_name"].nunique()

450

In [34]:
box_df.head()

      score                      image_name   x0   y0   x1   y1
0  0.789916  Electronics Complex PS5__1.jpg  197  112  297  136
1  0.520320        Baguiati PS514-18__1.jpg  443  126  696  150
2  0.921957      Baguiati PS509-2021__1.jpg  495  142  648  169
3  0.904128        Baguiati PS514-19__1.jpg  485  160  636  184
4  0.935657        Baguiati PS523-18__1.jpg  509  142  646  164

In [35]:
box_df_cp = box_df.copy()

In [36]:
box_df_cp = box_df_cp.drop_duplicates(subset="image_name", keep="first")

In [37]:
len(box_df_cp)

450

In [38]:
box_df_cp.head()

      score                      image_name   x0   y0   x1   y1
0  0.789916  Electronics Complex PS5__1.jpg  197  112  297  136
1  0.520320        Baguiati PS514-18__1.jpg  443  126  696  150
2  0.921957      Baguiati PS509-2021__1.jpg  495  142  648  169
3  0.904128        Baguiati PS514-19__1.jpg  485  160  636  184
4  0.935657        Baguiati PS523-18__1.jpg  509  142  646  164

In [39]:
box_df_cp= box_df_cp.sort_values(by= "image_name", axis=0 )

In [40]:
box_df_cp.head()

        score                               image_name   x0   y0   x1   y1
331  0.869296  Airport PSAIRPORT-0004-2017-2711__1.jpg  559   83  653  110
170  0.964737  Airport PSAIRPORT-0004-2018-3503__1.jpg  393  152  529  178
339  0.717034  Airport PSAIRPORT-0005-2017-3336__1.jpg  462   65  595   88
40   0.662735  Airport PSAIRPORT-0006-2017-3301__1.jpg  535   81  689  108
485  0.734326  Airport PSAIRPORT-0006-2018-1899__1.jpg  432  120  639  151

In [41]:
img_name_df = pd.DataFrame(box_df_cp["image_name"])

In [42]:
img_name_df.head()

                                  image_name
331  Airport PSAIRPORT-0004-2017-2711__1.jpg
170  Airport PSAIRPORT-0004-2018-3503__1.jpg
339  Airport PSAIRPORT-0005-2017-3336__1.jpg
40   Airport PSAIRPORT-0006-2017-3301__1.jpg
485  Airport PSAIRPORT-0006-2018-1899__1.jpg

In [43]:
import numpy as np

In [44]:
image_names= np.array(img_name_df["image_name"])

In [45]:
len(image_names)

450

In [46]:
with open("image_names.txt", "w") as outfile:
    outfile.write("\n".join(image_names))

In [47]:
box_df_cp.drop(columns = ["score"], inplace=True)

In [49]:
box_df_cp.to_csv("box_coordinates.csv", index=False)

In [50]:
import os

In [52]:
import numpy as np

In [53]:
coord = np.array([box_df_cp["x0"], box_df_cp["y0"], box_df_cp["x1"], box_df_cp["y1"]])

In [54]:
coord= np.transpose(coord)

In [55]:
len(coord)

450

In [56]:
from draw import save_boxed_imgs

In [57]:
save_boxed_imgs(image_names,coord)